import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import {
  collectCargoArtifacts,
  materializeCargoInputs,
  parseCargoLock,
} from "./materialize-cargo-inputs.mjs";

const experimentRoot = dirname(fileURLToPath(import.meta.url));

test("Cargo.lock parsing returns only checksummed crates.io packages", () => {
  const parsed = parseCargoLock(`# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "local-package"\nversion = "1.0.0"\n\n[[package]]\nname = "registry-package"\nversion = "2.3.4"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\nchecksum = "${"a".repeat(64)}"\n`);
  assert.equal(parsed.packages.length, 2);
  assert.deepEqual(parsed.registryPackages, [{
    name: "registry-package",
    version: "2.3.4",
    sha256: "a".repeat(64),
  }]);
  assert.equal(parsed.gitSourceCount, 0);
});

test("Cargo.lock parsing rejects missing registry checksums and duplicate identities", () => {
  assert.throws(
    () => parseCargoLock(`version = 4\n\n[[package]]\nname = "missing"\nversion = "1.0.0"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\n`),
    /checksum is missing or invalid/,
  );
  assert.throws(
    () => parseCargoLock(`version = 4\n\n[[package]]\nname = "same"\nversion = "1.0.0"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\nchecksum = "${"a".repeat(64)}"\n\n[[package]]\nname = "same"\nversion = "1.0.0"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\nchecksum = "${"a".repeat(64)}"\n`),
    /Duplicate Cargo registry package/,
  );
});

test("Cargo.lock parsing inventories Git sources so resolution can reject them", () => {
  const parsed = parseCargoLock(`version = 4\n\n[[package]]\nname = "git-package"\nversion = "1.0.0"\nsource = "git+https://example.invalid/repository#${"b".repeat(40)}"\n`);
  assert.equal(parsed.gitSourceCount, 1);
  assert.equal(parsed.registryPackages.length, 0);
});

test("the checked-in Cargo archive lock is complete, canonical, and byte-locked", () => {
  const lock = JSON.parse(readFileSync(resolve(experimentRoot, "cargo-inputs.lock.json"), "utf8"));
  const artifacts = collectCargoArtifacts(lock);
  assert.equal(artifacts.length, 181);
  assert.equal(artifacts.reduce((total, artifact) => total + artifact.bytes, 0), lock.totalArchiveBytes);
});

test("a locked Cargo archive is accepted offline and byte drift is rejected", async () => {
  await withFixture(async ({ artifact, bytes, lockPath, output }) => {
    const archives = resolve(output, "archives");
    mkdirSync(archives, { recursive: true });
    writeFileSync(resolve(archives, artifact.filename), bytes);
    const result = await materializeCargoInputs({ outputDirectory: output, offline: true, lockPath });
    assert.equal(result.artifacts.length, 1);
    assert.equal(result.artifacts[0].source, "existing");

    writeFileSync(resolve(archives, artifact.filename), "drift\n");
    await assert.rejects(
      materializeCargoInputs({ outputDirectory: output, offline: true, lockPath }),
      /expected .* bytes/,
    );
  });
});

test("a noncanonical Cargo archive URL and unsafe version are rejected", async () => {
  await withFixture(async ({ lockPath, output }) => {
    const lock = JSON.parse(readFileSync(lockPath, "utf8"));
    lock.archives[0].url = "https://example.invalid/fixture.crate";
    writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
    await assert.rejects(
      materializeCargoInputs({ outputDirectory: output, offline: true, lockPath }),
      /URL is not canonical/,
    );
  });

  await withFixture(async ({ lockPath, output }) => {
    const lock = JSON.parse(readFileSync(lockPath, "utf8"));
    lock.archives[0].version = "../escape";
    writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
    await assert.rejects(
      materializeCargoInputs({ outputDirectory: output, offline: true, lockPath }),
      /version is invalid/,
    );
  });
});

test("locked .crate files produce a reusable and drift-checked Cargo directory source", async () => {
  await withCrateFixture(async ({ artifact, lockPath, output }) => {
    const result = await materializeCargoInputs({
      outputDirectory: output,
      offline: true,
      prepareDirectorySource: true,
      lockPath,
    });
    assert.equal(result.directorySource.source, "created");
    assert.equal(result.directorySource.packageCount, 1);
    assert.match(result.directorySource.configPath, /config\.toml$/);
    assert.match(readFileSync(result.directorySource.configPath, "utf8"), /offline = true/);
    const packageRoot = resolve(output, "vendor", "fixture-crate-1.2.3");
    const checksum = JSON.parse(readFileSync(resolve(packageRoot, ".cargo-checksum.json"), "utf8"));
    assert.equal(checksum.package, artifact.sha256);
    assert.match(checksum.files["src/lib.rs"], /^[0-9a-f]{64}$/);

    const reused = await materializeCargoInputs({
      outputDirectory: output,
      offline: true,
      prepareDirectorySource: true,
      lockPath,
    });
    assert.equal(reused.directorySource.source, "existing");

    writeFileSync(resolve(packageRoot, "src/lib.rs"), "pub fn drift() {}\n");
    await assert.rejects(
      materializeCargoInputs({
        outputDirectory: output,
        offline: true,
        prepareDirectorySource: true,
        lockPath,
      }),
      /Cargo vendor file drifted/,
    );
  });
});

async function withFixture(callback) {
  const root = mkdtempSync(resolve(tmpdir(), "autojs6-cargo-input-test-"));
  try {
    const bytes = Buffer.from("locked Cargo archive\n", "utf8");
    const artifact = {
      name: "fixture-crate",
      version: "1.2.3",
      filename: "fixture-crate-1.2.3.crate",
      url: "https://static.crates.io/crates/fixture-crate/fixture-crate-1.2.3.crate",
      bytes: bytes.length,
      sha256: createHash("sha256").update(bytes).digest("hex"),
    };
    const lockPath = resolve(root, "cargo-inputs.lock.json");
    writeFileSync(lockPath, `${JSON.stringify({
      schemaVersion: 1,
      snapshotDate: "2026-09-03",
      bunCommit: "778ce669a38888457c36cab0f2231c3f25592b7d",
      cargoLock: {
        path: "Cargo.lock",
        bytes: 70318,
        gitBlobSha1: "28c08e1b7bc188aa32a7d5ba3fc7647f616fe749",
        sha256: "819a552d52819d4d33897df69e16b698d703cec4e9009c2d132791931ab40856",
        packageCount: 284,
        registryPackageCount: 1,
        gitSourceCount: 0,
      },
      registrySource: "registry+https://github.com/rust-lang/crates.io-index",
      archiveUrlPattern: "https://static.crates.io/crates/{name}/{name}-{version}.crate",
      archiveCount: 1,
      totalArchiveBytes: bytes.length,
      archives: [artifact],
      readiness: {
        archiveIdentitiesLockedByCargo: true,
        archiveByteCountsLockedByProject: true,
        archivesMaterializedAndVerified: true,
        offlineSourceReplacementReady: false,
      },
    }, null, 2)}\n`);
    await callback({ artifact, bytes, lockPath, output: resolve(root, "materialized") });
  } finally {
    rmSync(root, { force: true, recursive: true });
  }
}

async function withCrateFixture(callback) {
  const root = mkdtempSync(resolve(tmpdir(), "autojs6-cargo-directory-source-test-"));
  try {
    const packageRoot = "fixture-crate-1.2.3";
    const content = resolve(root, "content", packageRoot);
    mkdirSync(resolve(content, "src"), { recursive: true });
    writeFileSync(resolve(content, "Cargo.toml"), "[package]\nname = \"fixture-crate\"\nversion = \"1.2.3\"\nedition = \"2021\"\n");
    writeFileSync(resolve(content, "src/lib.rs"), "pub fn fixture() {}\n");
    const output = resolve(root, "materialized");
    const archiveDirectory = resolve(output, "archives");
    mkdirSync(archiveDirectory, { recursive: true });
    const archive = resolve(archiveDirectory, `${packageRoot}.crate`);
    const tarExecutable = process.platform === "win32" && process.env.SystemRoot
      ? resolve(process.env.SystemRoot, "System32", "tar.exe")
      : "tar";
    const tar = spawnSync(tarExecutable, ["-czf", archive, "-C", resolve(root, "content"), packageRoot], {
      encoding: "utf8",
      windowsHide: true,
    });
    if (tar.error) throw tar.error;
    assert.equal(tar.status, 0, tar.stderr);
    assert.equal(existsSync(archive), true);
    const bytes = readFileSync(archive);
    const artifact = {
      name: "fixture-crate",
      version: "1.2.3",
      filename: `${packageRoot}.crate`,
      url: `https://static.crates.io/crates/fixture-crate/${packageRoot}.crate`,
      bytes: bytes.length,
      sha256: createHash("sha256").update(bytes).digest("hex"),
    };
    const lockPath = resolve(root, "cargo-inputs.lock.json");
    writeFileSync(lockPath, `${JSON.stringify(createFixtureLock(artifact), null, 2)}\n`);
    await callback({ artifact, lockPath, output });
  } finally {
    rmSync(root, { force: true, recursive: true });
  }
}

function createFixtureLock(artifact) {
  return {
    schemaVersion: 1,
    snapshotDate: "2026-09-03",
    bunCommit: "778ce669a38888457c36cab0f2231c3f25592b7d",
    cargoLock: {
      path: "Cargo.lock",
      bytes: 70318,
      gitBlobSha1: "28c08e1b7bc188aa32a7d5ba3fc7647f616fe749",
      sha256: "819a552d52819d4d33897df69e16b698d703cec4e9009c2d132791931ab40856",
      packageCount: 284,
      registryPackageCount: 1,
      gitSourceCount: 0,
    },
    registrySource: "registry+https://github.com/rust-lang/crates.io-index",
    archiveUrlPattern: "https://static.crates.io/crates/{name}/{name}-{version}.crate",
    archiveCount: 1,
    totalArchiveBytes: artifact.bytes,
    archives: [artifact],
    readiness: {
      archiveIdentitiesLockedByCargo: true,
      archiveByteCountsLockedByProject: true,
      archivesMaterializedAndVerified: true,
      offlineSourceReplacementReady: false,
    },
  };
}
